# ===================================
#  Relation Behavior Config
# ===================================

posts:
    label: Posts
    view:
        list: $/rainlab/blog/models/post/columns.yaml
        toolbarButtons: add|remove
    manage:
        form: $/rainlab/blog/models/post/fields.yaml
        recordsPerPage: 10

related:
    label: Related Series
    view:
        list: $/pkleindienst/blogseries/models/related/columns.yaml
        toolbarButtons: add|remove
    manage:
        list: $/pkleindienst/blogseries/models/related/columns.yaml
        recordsPerPage: 10
        scope: noSelfRelation